# Generated by Django 4.2.28 on 2026-02-12 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('policiais', 'Carreiras Policiais'), ('militares', 'Carreiras Militares'), ('fiscais', 'Carreiras Fiscais'), ('juridicas', 'Carreiras Jurídicas'), ('bancarias', 'Carreiras Bancárias'), ('educacao', 'Educação'), ('saude', 'Saúde'), ('administrativa', 'Administrativa'), ('ti', 'TI'), ('engenharia', 'Engenharia'), ('fiscalizacao', 'Fiscalização'), ('logistica', 'Logística'), ('legislativa', 'Legislativa'), ('enem_vestibular', 'ENEM/Vestibulares')], max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(default='book', max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Cor')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Requer Premium')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='modules.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Estimadas')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='modules.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['module', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Horas Estudadas')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='modules.subject', verbose_name='Disciplina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Estudo',
                'verbose_name_plural': 'Sessões de Estudo',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Hora Início')),
                ('end_time', models.TimeField(verbose_name='Hora Fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='modules.subject', verbose_name='Disciplina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de conclusão', max_digits=5, verbose_name='Percentual')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total de Horas')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('last_studied', models.DateField(blank=True, null=True, verbose_name='Último Estudo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='modules.subject', verbose_name='Disciplina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso',
                'verbose_name_plural': 'Progressos',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
