# Generated by Django 5.1.15 on 2026-02-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='background_image',
            field=models.URLField(blank=True, help_text='URL da imagem de fundo do card', max_length=500, verbose_name='Imagem de Fundo'),
        ),
    ]
