# Generated by Django 4.2.28 on 2026-02-12 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Sequência Atual')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Maior Sequência')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='Última Data de Estudo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_streak', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sequência de Estudos',
                'verbose_name_plural': 'Sequências de Estudos',
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('target_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Meta de Horas')),
                ('start_date', models.DateField(verbose_name='Data Início')),
                ('end_date', models.DateField(verbose_name='Data Fim')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta de Estudo',
                'verbose_name_plural': 'Metas de Estudo',
                'ordering': ['-start_date'],
            },
        ),
    ]
