# Generated by Django 4.2.28 on 2026-02-12 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('plan_type', models.CharField(choices=[('free', 'Gratuito'), ('pro', 'Pro')], max_length=20, unique=True, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Mensal')),
                ('features', models.TextField(help_text='Um recurso por linha', verbose_name='Recursos')),
                ('max_categories', models.IntegerField(default=3, verbose_name='Máximo de Categorias')),
                ('max_modules', models.IntegerField(default=10, verbose_name='Máximo de Módulos')),
                ('has_premium_categories', models.BooleanField(default=False, verbose_name='Acesso a Categorias Premium')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Relatórios Avançados')),
                ('has_export', models.BooleanField(default=False, verbose_name='Exportar Dados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('trial', 'Período de Teste')], default='active', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Última Data de Pagamento')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='Próxima Data de Pagamento')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovação Automática')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
