# Generated by Django 5.1.15 on 2026-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_category_background_image'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Módulos que este plano permite acessar', related_name='plans', to='modules.module', verbose_name='Módulos Inclusos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Gratuito'), ('police', 'Carreira Policial'), ('bank', 'Carreira Bancária'), ('enem', 'ENEM/Vestibular'), ('military', 'Carreira Militar'), ('legal', 'Carreira Jurídica'), ('fiscal', 'Carreira Fiscal'), ('pro', 'Pro - Acesso Total')], max_length=20, unique=True, verbose_name='Tipo'),
        ),
    ]
